// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interface.go -destination=internal/repository/mock_interface.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// BatchInsert mocks base method.
func (m *MockRepositoryInterface) BatchInsert(req *BatchInsertRequest) (*BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", req)
	ret0, _ := ret[0].(*BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockRepositoryInterfaceMockRecorder) BatchInsert(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockRepositoryInterface)(nil).BatchInsert), req)
}

// BatchLogicalDelete mocks base method.
func (m *MockRepositoryInterface) BatchLogicalDelete(req *BatchDeleteRequest) (*BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchLogicalDelete", req)
	ret0, _ := ret[0].(*BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchLogicalDelete indicates an expected call of BatchLogicalDelete.
func (mr *MockRepositoryInterfaceMockRecorder) BatchLogicalDelete(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchLogicalDelete", reflect.TypeOf((*MockRepositoryInterface)(nil).BatchLogicalDelete), req)
}

// BatchUpdate mocks base method.
func (m *MockRepositoryInterface) BatchUpdate(req *BatchUpdateRequest) (*BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", req)
	ret0, _ := ret[0].(*BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockRepositoryInterfaceMockRecorder) BatchUpdate(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockRepositoryInterface)(nil).BatchUpdate), req)
}

// GetTableSchema mocks base method.
func (m *MockRepositoryInterface) GetTableSchema(tableName string) (*TableSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableSchema", tableName)
	ret0, _ := ret[0].(*TableSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableSchema indicates an expected call of GetTableSchema.
func (mr *MockRepositoryInterfaceMockRecorder) GetTableSchema(tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableSchema", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTableSchema), tableName)
}

// Insert mocks base method.
func (m *MockRepositoryInterface) Insert(req *InsertRequest) (*MutationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", req)
	ret0, _ := ret[0].(*MutationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockRepositoryInterfaceMockRecorder) Insert(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRepositoryInterface)(nil).Insert), req)
}

// JoinQuery mocks base method.
func (m *MockRepositoryInterface) JoinQuery(req *JoinRequest) (*QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinQuery", req)
	ret0, _ := ret[0].(*QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinQuery indicates an expected call of JoinQuery.
func (mr *MockRepositoryInterfaceMockRecorder) JoinQuery(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinQuery", reflect.TypeOf((*MockRepositoryInterface)(nil).JoinQuery), req)
}

// LogicalDelete mocks base method.
func (m *MockRepositoryInterface) LogicalDelete(req *DeleteRequest) (*MutationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogicalDelete", req)
	ret0, _ := ret[0].(*MutationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogicalDelete indicates an expected call of LogicalDelete.
func (mr *MockRepositoryInterfaceMockRecorder) LogicalDelete(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogicalDelete", reflect.TypeOf((*MockRepositoryInterface)(nil).LogicalDelete), req)
}

// Query mocks base method.
func (m *MockRepositoryInterface) Query(req *QueryRequest) (*QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", req)
	ret0, _ := ret[0].(*QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockRepositoryInterfaceMockRecorder) Query(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockRepositoryInterface)(nil).Query), req)
}

// Update mocks base method.
func (m *MockRepositoryInterface) Update(req *UpdateRequest) (*MutationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", req)
	ret0, _ := ret[0].(*MutationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryInterfaceMockRecorder) Update(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepositoryInterface)(nil).Update), req)
}
