// Code generated by MockGen. DO NOT EDIT.
// Source: internal/driver/driver.go
//
// Generated by this command:
//
//	mockgen -source=internal/driver/driver.go -destination=internal/driver/mock_driver.go -package=driver
//

// Package driver is a generated GoMock package.
package driver

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseDriver is a mock of DatabaseDriver interface.
type MockDatabaseDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseDriverMockRecorder
	isgomock struct{}
}

// MockDatabaseDriverMockRecorder is the mock recorder for MockDatabaseDriver.
type MockDatabaseDriverMockRecorder struct {
	mock *MockDatabaseDriver
}

// NewMockDatabaseDriver creates a new mock instance.
func NewMockDatabaseDriver(ctrl *gomock.Controller) *MockDatabaseDriver {
	mock := &MockDatabaseDriver{ctrl: ctrl}
	mock.recorder = &MockDatabaseDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseDriver) EXPECT() *MockDatabaseDriverMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockDatabaseDriver) BatchDelete(ctx context.Context, req *BatchDeleteRequest) (*BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, req)
	ret0, _ := ret[0].(*BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockDatabaseDriverMockRecorder) BatchDelete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockDatabaseDriver)(nil).BatchDelete), ctx, req)
}

// BatchInsert mocks base method.
func (m *MockDatabaseDriver) BatchInsert(ctx context.Context, req *BatchInsertRequest) (*BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", ctx, req)
	ret0, _ := ret[0].(*BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockDatabaseDriverMockRecorder) BatchInsert(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockDatabaseDriver)(nil).BatchInsert), ctx, req)
}

// BatchUpdate mocks base method.
func (m *MockDatabaseDriver) BatchUpdate(ctx context.Context, req *BatchUpdateRequest) (*BatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, req)
	ret0, _ := ret[0].(*BatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockDatabaseDriverMockRecorder) BatchUpdate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockDatabaseDriver)(nil).BatchUpdate), ctx, req)
}

// Close mocks base method.
func (m *MockDatabaseDriver) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseDriverMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabaseDriver)(nil).Close))
}

// CurrentDatabase mocks base method.
func (m *MockDatabaseDriver) CurrentDatabase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentDatabase")
	ret0, _ := ret[0].(string)
	return ret0
}

// CurrentDatabase indicates an expected call of CurrentDatabase.
func (mr *MockDatabaseDriverMockRecorder) CurrentDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentDatabase", reflect.TypeOf((*MockDatabaseDriver)(nil).CurrentDatabase))
}

// Delete mocks base method.
func (m *MockDatabaseDriver) Delete(ctx context.Context, req *DeleteRequest) (*MutationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*MutationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDatabaseDriverMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDatabaseDriver)(nil).Delete), ctx, req)
}

// DriverType mocks base method.
func (m *MockDatabaseDriver) DriverType() DriverType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverType")
	ret0, _ := ret[0].(DriverType)
	return ret0
}

// DriverType indicates an expected call of DriverType.
func (mr *MockDatabaseDriverMockRecorder) DriverType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverType", reflect.TypeOf((*MockDatabaseDriver)(nil).DriverType))
}

// GetTableSchema mocks base method.
func (m *MockDatabaseDriver) GetTableSchema(tableName string) (*TableSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableSchema", tableName)
	ret0, _ := ret[0].(*TableSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableSchema indicates an expected call of GetTableSchema.
func (mr *MockDatabaseDriverMockRecorder) GetTableSchema(tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableSchema", reflect.TypeOf((*MockDatabaseDriver)(nil).GetTableSchema), tableName)
}

// Insert mocks base method.
func (m *MockDatabaseDriver) Insert(ctx context.Context, req *InsertRequest) (*MutationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, req)
	ret0, _ := ret[0].(*MutationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDatabaseDriverMockRecorder) Insert(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDatabaseDriver)(nil).Insert), ctx, req)
}

// JoinQuery mocks base method.
func (m *MockDatabaseDriver) JoinQuery(ctx context.Context, req *JoinRequest) (*QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinQuery", ctx, req)
	ret0, _ := ret[0].(*QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinQuery indicates an expected call of JoinQuery.
func (mr *MockDatabaseDriverMockRecorder) JoinQuery(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinQuery", reflect.TypeOf((*MockDatabaseDriver)(nil).JoinQuery), ctx, req)
}

// Ping mocks base method.
func (m *MockDatabaseDriver) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDatabaseDriverMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDatabaseDriver)(nil).Ping), ctx)
}

// Query mocks base method.
func (m *MockDatabaseDriver) Query(ctx context.Context, req *QueryRequest) (*QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, req)
	ret0, _ := ret[0].(*QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDatabaseDriverMockRecorder) Query(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDatabaseDriver)(nil).Query), ctx, req)
}

// Update mocks base method.
func (m *MockDatabaseDriver) Update(ctx context.Context, req *UpdateRequest) (*MutationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*MutationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDatabaseDriverMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDatabaseDriver)(nil).Update), ctx, req)
}

// UseDatabase mocks base method.
func (m *MockDatabaseDriver) UseDatabase(database string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseDatabase", database)
	ret0, _ := ret[0].(error)
	return ret0
}

// UseDatabase indicates an expected call of UseDatabase.
func (mr *MockDatabaseDriverMockRecorder) UseDatabase(database any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseDatabase", reflect.TypeOf((*MockDatabaseDriver)(nil).UseDatabase), database)
}
